### PR TITLE
Update Solution

### PR DESCRIPTION
**Pull request by BenGitsCode**
Refresh for cohort 016

### CODE REVIEW

**Comment by jrhorn424** [comment]
@BenGitsCode Please rebase against current master and fix any conflicts, then tag me for a review.

**Comment by payne-chris-r** [comment]
I think this should be closed at this point @BenGitsCode

**Comment by MicFin** [comment]
@BenGitsCode please close.  `lm01` incorporated the updates from this `016` branch. https://github.com/ga-wdi-boston/git-diagnostic/commit/373a89fbb726ad55a193a1ed1f5a1a749d81463b

**Comment by BenGitsCode** [comment]
Closed per above comment.

**Comment by MicFin** [comment]
@BenGitsCode Wait not on your vacation!

**Pull request closed without merging**
